var textsJSON = { 
    general_texts : [
        {
            footer_text : "Nota: Si el estudiante, una vez matriculado en el COLEGIO ROCHESTER se retira antes de la fecha de iniciación de clases del año escolar 2019-2020, se le devolverá; el 50% del valor de la matrícula y el 100% de los otros costos pagados. Si el estudiante se retira después de iniciadas las clases, no habrá; lugar a devolver suma alguna del valor de la matrícula, y se le devolverá lo pagado por otros conceptos de costos proporcionalmente al tiempo de permanencia en EL COLEGIO.",
            no_davivienda_payment: "Apreciado Padre de Familia, nuestro sistema no registra el número de la tarjeta de crédito Diners - Davivienda. Agradecemos acercarse al area de facturación adjuntando los documentos requeridos para realizar el proceso de solicitud de la tarjeta de crédito. En caso de que decida realizar el pago anticipado del año escolar es necesario que envíe un correo a <code>cartera@rochester.edu.co</code> manifestando su intención de pago anticipado, junto con la matrácula.<br /><br /> <p>Para realizar la solicitud de la tarjeta davivienda se requiere anexar los siguientes documentos:</p> <ul> <li><strong>Para empleados</strong>: Fotocopia de la c&eacute;dula ampliada al 150% , los tres &uacute;ltimos desprendibles de pago de n&oacute;mina y la certificaci&oacute;n laboral.</li> <li><strong>Para independientes</strong>: Fotocopia de la c&eacute;dula ampliada al 150%, declaraci&oacute;n de renta y tres extractos bancarios de los &uacute;ltimos meses.</li> </ul>",
            no_financial_auth: "<b><u>Apreciado Padre de Familia, nuestro sistema registra un saldo pendiente de pago a la fecha.</u></b><br/><br/> Por favor ingrese al siguiente link: <a href='https://finances.rochester.edu.co' target='_blank'>https://finances.rochester.edu.co</a>, para cancelar la deuda. Es necesario enviar el soporte al correo <code>cartera@rochester.edu.co</code> para generar paz y salvo y desbloqueo de la plataforma de matrículas.",
            anticipated_payment: "<center>Agradecemos el pago anticipado realizado para el año escolar 2019-2020.</center><br/><br/>Por favor seleccione los servicios que va a tomar y envíe un correo a <code>cartera@rochester.edu.co</code> adjuntando el pdf de la <b>FACTURA ANUAL DE SERVICIOS CONTRATADOS</b> generado por la plataforma, con el fin de generar su nueva liquidación.",
            both_davivienda_financial: "<b><u>Apreciado Padre de Familia, nuestro sistema registra un saldo pendiente de pago a la fecha</b></u>. Por favor ingrese al siguiente link: <a href='https://finances.rochester.edu.co' target='_blank'>https://finances.rochester.edu.co</a>. Adicionalmente es indispensable realizar la solicitud de la tarjeta Diners-Davivienda para lo cual es necesario acercarse a la oficina de Facturación.",
            no_academic_auth: "<b><u>El estudiante no esta autorizado academicamente para la matrícula</u></b>, por favor comuníquese con el director de nivel, exclusivamente a través de correo electrónico o mensaje vía Schoology.",
            empty_result: "No se encontraron resultados para el código ingresado. Verifique el código del estudiante e intente nuevamente.",
            wrong_code: "El código del estudiante debe tener una extensión de <b>5 dígitos</b>. Por favor verifiquelo e intente nuevamente.",
            payment_method_text: "<ul><li><b>Año anticipado:</b> Matrícula y 10 mensualidades anticipadas con el 5% de descuento. En el pago en línea pagaría matrícula y 10 mensualidades.</li><li><b>Semestral:</b> Matrícula y 5 mensualidades anticipadas con el 2.5% de descuento. En el pago en línea pagaría matrícula y 5 mensualidades. En diciembre deberá pagar las 5 mensualidades restantes.</li><li><b>Mensual:</b> Mantrícula y 10 pagos a realizar de manera mensual. En el pago en línea pagaría la matrícula y las mensualidades las pagaría a través del convenio con Davivienda mensualmente.</li></ul>",
            donation_help: "(<b>Elija 1, 2 ó 3 proyectos</b> en los que quisiera que se dividiera su aporte)",
            authorized_people_eco: "Información de las personas autorizadas para recoger al estudiante en el paradero o en el Colegio:",
            help_step1: "<p style='text-align: left;'>En esta secci&oacute;n, usted encontrar&aacute; dos tipos de informaci&oacute;n:</p><div> <ul> <li style='text-align: left;'>En la columna izquierda, bajo el t&iacute;tulo de 'conceptos', usted encontrar&aacute; un resumen de los valores que corresponden &uacute;nicamente al costo de la matr&iacute;cula anual para el estudiante. Adem&aacute;s, encontrar&aacute; la informaci&oacute;n respectiva frente a las 'becas' o descuentos que aplican para el estudiante de acuerdo con los criterios que se presentan. Estos valores se reflejan en un resumen total.</li> <li style='text-align: left;'>En la columna derecha, bajo el t&iacute;tulo de&nbsp;'servicios adicionales', usted deber&aacute; seleccionar qu&eacute; servicio o servicios desea adquirir teniendo en cuenta que son adicionales al costo de la matr&iacute;cula y son cobros anuales.</li> </ul></div> <p>En la columna derecha y en caja verde, usted encontrar&aacute; el t&iacute;tulo 'Total a pagar'&nbsp; que hace referencia al resumen del valor total a pagar sobre el costo de la matr&iacute;cula m&aacute;s los servicios adicionales que haya seleccionado.&nbsp;</p>",
            help_step2: "<p>En esta secci&oacute;n usted podr&aacute; seleccionar los servicios&nbsp;a los que desea acceder cada mes durante 10 meses (agosto a mayo), incluido el valor de la pensi&oacute;n.&nbsp;</p>",
            help_step3: "<p>En esta secci&oacute;n usted encontrar&aacute; la siguiente informaci&oacute;n correspondiente a las actividades extracurriculares y del Club Deportivo Rochester:</p> <ul> <li>Primero, usted deber&aacute; incluir la informaci&oacute;n relacionada con el servicio de transporte extracurricular que desea adquirir y la informaci&oacute;n de las personas autorizadas para recoger al estudiante en los paraderos de las rutas o en el Colegio (seg&uacute;n la modalidad que usted haya seleccionado).&nbsp;</li> <li>En segundo lugar, usted encuentrar&aacute; la oferta de las actividades extracurriculares y del Club Deportivo Rochester que apliquen y se ajusten al grado del estudiante. El valor presentado hace referencia a un costo mensual y podr&aacute; elegir la actividad de su preferencia haciendo clic en el bot&oacute;n 'inscribir'.</li> <li>En la caja verde de la columna derecha, donde aperece el t&iacute;tulo 'Total a pagar', usted encontrar&aacute; el monto equivalente a un mes de la o las actividades extracurriculares y del servicio de transporte que usted inscribi&oacute;.</li> </ul>",
        }
    ]
}

export default textsJSON